# -*- coding: utf-8 -*-
"""XLA_TH1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcRWNwA_GUKvw-SydEUBqBU2ZVq58Sx0
"""

a=5
b=2
print(a+b)

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

img1 = plt.imread('/content/drive/MyDrive/XuLyAnh/TH1/TH1/Photo00002.jpg')
plt.imshow(img1)

r = img1[:,:,0]   #Lấy kênh màu đỏ vì reb ở vị trí số 0 trong (R,G,B)
plt.imshow(r,cmap='gray')

type(img1)
print(f'Shape: {img1.shape}')
print(f'ndim: {img1.ndim}')
print(f'size: {img1.size}')
print(f'dtype: {img1.dtype}')
print(f'nbytes: {img1.nbytes}')

"""
- Shap dùng để hiển thị kích thước hình ảnh, dưới dạng (height,withd,channels)
- ndim: thường dùng để hiển thị số chiều của hình ảnh, ảnh mức xám thì in ra giá trị là 2 , ảnh màu thì giá trị là 3
- size: dùng để hiển thị tổng phần tử trong ảnh.
- dtype: dùng để hiển thị kiểu dữ liệu của mỗi phần tử ảnh.
- nbytes: dùng để hiển thị tổng kích thước của hình ảnh trong bộ nhớ."""

hist, bins = np.histogram(r.ravel(), bins=256, range=(0,256))
plt.title("Red histogram")
plt.bar(bins[:-1],hist)

plt.subplots(nrows = 2, ncols=2)    #Tạo ra 1 figure có 2 hàng và 2 cột

# Hiển thị ảnh gốc
plt.subplot(2,2,1)      #(số hàng:2, số cột:2 ,vị trí xuất hiện:1)
plt.title('Original image')
plt.imshow(img1)

#Hiển thị tổ chức đồ của kênh màu đỏ
r = img1[:,:,0]
hist, bins = np.histogram(r.ravel(), bins=256, range=(0,256))
plt.subplot(2,2,2)      #(số hàng:2, số cột:2 ,vị trí xuất hiện:2)
plt.title("Reb histogram")
plt.bar(bins[:-1], hist)

#Hiển thị tổ chức đồ của kênh màu xanh lá
g = img1[:,:,1]
hist, bins = np.histogram(g.ravel(), bins=256, range=(0,256))
plt.subplot(2,2,3)       #(số hàng:2, số cột:2 ,vị trí xuất hiện:3)
plt.title("Green histogram")
plt.bar(bins[:-1], hist)

#Hiển thị tổ chức đồ của kênh màu xanh dương
b = img1[:,:,2]
hist, bins = np.histogram(b.ravel(), bins=256, range=(0,256))
plt.subplot(2,2,4)       #(số hàng:2, số cột:2 ,vị trí xuất hiện:4)
plt.title("Blue histogram")
plt.bar(bins[:-1], hist)